name: Branch Build (non-default & forks)

on:
  push:
    branches-ignore:
      - master
      - main

permissions:
  contents: read

concurrency:
  group: branch-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --no-restore --configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bins-Release
          path: '**/bin/Release/**'
