name: CI Build & Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # adjust if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release --output ./build_output

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clankboard-Build
          path: ./build_output
