name: General Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # match your SDK

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release --output ./build_output

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Clankboard-Build
          path: ./build_output
